# Use new container infrastructure to enable caching
sudo: required
dist: xenial

language: go
go:
  - 1.9.x

addons:
  apt:
    packages:
    - libgmp-dev
    - build-essential
    - cmake
    - git
    - libgtk2.0-dev
    - pkg-config
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libtbb2
    - libtbb-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libjasper-dev
    - libdc1394-22-dev
    - xvfb
    - nvidia-profiler
    - nvidia-cuda-dev
    - nvidia-cuda-toolkit
    - libcudnn7

before_install:
  - ./travis_build_opencv.sh
  - export PKG_CONFIG_PATH=$(pkg-config --variable pc_path pkg-config):$HOME/usr/lib/pkgconfig
  - export INCLUDE_PATH=$HOME/usr/include:${INCLUDE_PATH}
  - export LD_LIBRARY_PATH=$HOME/usr/lib:${LD_LIBRARY_PATH}
  - sudo ln /dev/null /dev/raw1394
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo bash ./travis_build_cuda.sh
  - sudo bash ./travis_build_darknet.sh
  - sudo apt-get -qq update

before_cache:
  - rm -f $HOME/fresh-cache

services: mongodb

install:
  - make build

script:
  - export CGO_CPPFLAGS="-I${HOME}/usr/include"
  - export CGO_LDFLAGS="-L${HOME}/usr/lib -lopencv_core -lopencv_videoio -lopencv_face -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_objdetect -lopencv_features2d -lopencv_video -lopencv_dnn -lopencv_xfeatures2d"
  - make test_coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Caching so the next build will be fast as possible.
cache:
  timeout: 1000
  directories:
    - $HOME/usr
    - $HOME/testdata